import React, { useEffect, useState } from 'react';
import { GitMerge, Activity, ServerCog, CheckCircle, Database, SearchCode } from 'lucide-react';

interface Log {
  timestamp: string;
  mergedPendingId: string;
  newPostedId: string;
  confidenceScore: number;
  merchantName: string;
}

export default function ReconciliationDashboard() {
  const [logs, setLogs] = useState<Log[]>([]);
  const [loading, setLoading] = useState(false);
  const [triggering, setTriggering] = useState(false);

  const fetchLogs = async () => {
    try {
      const res = await fetch('/api/plaid/reconciliation-logs');
      const json = await res.json();
      if (json.success) setLogs(json.data);
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => {
    fetchLogs();
  }, []);

  const triggerWebhookMock = async () => {
    setTriggering(true);
    try {
      // Simulating the incoming Plaid webhook
      await fetch('/api/plaid/webhook', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          webhook_type: 'TRANSACTIONS',
          webhook_code: 'DEFAULT_UPDATE',
          item_id: 'mock_item_id_123',
          new_transactions: 2
        })
      });
      // Fetch the updated logs generated by the worker
      await fetchLogs();
    } catch (err) {
      console.error(err);
    } finally {
      setTriggering(false);
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto bg-white p-8 rounded-3xl shadow-sm border border-slate-100">
      
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 border-b border-slate-100 pb-6 gap-4">
        <div className="flex items-center gap-3">
          <div className="p-3 bg-emerald-50 text-emerald-600 rounded-xl">
            <ServerCog className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-slate-800">Deduplication Worker</h2>
            <p className="text-sm text-slate-500">
              Monitoring Plaid webhooks to automatically merge PENDING and POSTED transactions.
            </p>
          </div>
        </div>
        
        <button 
          onClick={triggerWebhookMock}
          disabled={triggering}
          className="flex items-center gap-2 px-5 py-2.5 bg-slate-900 text-white font-bold rounded-xl hover:bg-slate-800 disabled:opacity-50 transition-colors text-sm"
        >
          {triggering ? <Activity className="w-4 h-4 animate-spin" /> : <Database className="w-4 h-4" />}
          Simulate Plaid Webhook
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
        <div className="bg-slate-50 border border-slate-200 p-5 rounded-2xl flex flex-col justify-center">
          <p className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Worker Status</p>
          <p className="font-bold text-emerald-600 flex items-center gap-1.5">
            <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></div> Active
          </p>
        </div>
        <div className="bg-slate-50 border border-slate-200 p-5 rounded-2xl flex flex-col justify-center">
          <p className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Queue Backend</p>
          <p className="font-bold text-slate-800">Redis (BullMQ)</p>
        </div>
        <div className="bg-slate-50 border border-slate-200 p-5 rounded-2xl flex flex-col justify-center">
          <p className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Duplicates Prevented</p>
          <p className="font-black text-slate-800 text-2xl">{logs.length}</p>
        </div>
      </div>

      <div>
        <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wider mb-4">
          Recent Reconciliation Logs
        </h3>

        {logs.length === 0 ? (
          <div className="text-center p-12 bg-slate-50 text-slate-400 rounded-2xl border border-slate-100 border-dashed">
            <Activity className="w-8 h-8 mx-auto mb-3 opacity-30" />
            <p className="font-medium text-sm">Listening for incoming webhooks...</p>
            <p className="text-xs mt-1">Click the simulation button above to trigger an event.</p>
          </div>
        ) : (
          <div className="space-y-3 font-mono text-sm">
            {logs.map((log, idx) => (
              <div key={idx} className="bg-slate-900 text-slate-300 p-4 rounded-xl flex flex-col gap-2 relative overflow-hidden group">
                <div className="absolute top-0 left-0 w-1 h-full bg-indigo-500"></div>
                
                <div className="flex justify-between items-center text-xs text-slate-500 mb-1">
                  <span>[{new Date(log.timestamp).toLocaleTimeString()}] RECONCILIATION_SUCCESS</span>
                  <div className="flex items-center gap-1 bg-slate-800 px-2 py-0.5 rounded text-indigo-400 border border-slate-700">
                    <SearchCode className="w-3 h-3" />
                    Confidence: {(log.confidenceScore * 100).toFixed(0)}%
                  </div>
                </div>

                <div className="flex items-center gap-3 text-slate-200">
                  <span className="flex items-center gap-1.5"><GitMerge className="w-4 h-4 text-indigo-400" /> Merged</span>
                  <span className="text-slate-400">{log.mergedPendingId}</span>
                  <span className="text-slate-500">→</span>
                  <span className="text-emerald-400">{log.newPostedId}</span>
                </div>

                <div className="text-xs text-slate-400 flex items-center gap-1.5 mt-1">
                  <CheckCircle className="w-3.5 h-3.5 text-emerald-500" /> 
                  Updated merchant name from Pending to: <span className="font-bold text-slate-200">"{log.merchantName}"</span>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

    </div>
  );
}
